[package]
name = "cleaner"
version = "1.0.0"
edition = "2021"
description = "A native desktop application to reclaim disk space by cleaning build and dependency folders."
authors = ["David Mendez"]
license = "MIT"

[dependencies]
eframe = { version = "0.29", default-features = false, features = [
    "default_fonts",
    "wgpu",
    "wayland",
    "x11",
] }
egui = "0.29"
rfd = "0.15"
walkdir = "2.5"
crossbeam-channel = "0.5"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
